### PR TITLE
Fixed a bug with sending embeds

### PR DESCRIPTION
**Pull request by xartuu**
### Hello 
The error was related to retrieving the channel ID on which the user was sending the message. I fixed it in the first commit, and in the second one I removed the `console.log` command so it wouldn't clutter the console.

By the way, just a second ago I wanted to send embeds, and here the plugin doesn't work, so I'm coming with a fix ;D

### CODE REVIEW

**Review by Kevin-ArDev — APPROVED** [review]
works for me

**Comment by Danin12312** [comment]
> works for me
how?

**Comment by lesleyxyz** [comment]
@Fraserbc please approve

**Comment by Fraserbc** [comment]
Sorry for taking nearly a month to respond to this but thanks!

**Pull request merged**
